package com.bornfire.merchantqrcode.DataModel


data class UserData(
    val merchant_user_id: String,
    val merchant_name: String,
    val merchant_legal_user_id: String,
    val merchant_corporate_name: String,
    val user_id: String,
    val user_name: String,
    val user_designation: String,
    val user_role: String,
    val password1: String,
    val password_expiry_date1: String,
    val password_life1: String,
    val account_expiry_date1: String,
    val make_or_checker: String?,
    val supervisor_flag: String,
    val user_disable_flag1: String,
    val user_disable_from_date1: String,
    val user_disable_to_date1: String,
    val del_flag1: String,
    val user_status1: String,
    val login_status1: String,
    val login_channel1: String,
    val mobile_no1: String,
    val alternate_mobile_no1: String?,
    val email_address1: String,
    val alternate_email_id1: String,
    val default_device_id: String,
    val alternative_device_id1: String,
    val entry_user: String,
    val modify_user: String?,
    val verify_user: String?,
    val entry_time: String,
    val modify_time: String,
    val verify_time: String?,
    val alternative_device_id2: String,
    val unit_id_u:String,
    val unit_name_u:String,
    val unit_type_u:String,
    val entry_flag:String?,
    val modify_flag:String?,
    val countrycode:String,
    val authentication_flg:String,
    val alt_countrycode:String?,
    val  remark:String?,
    val  delete_time: String?,
    val  delete_user:String?
)
data class EncryptedRequest(val encryptedstring: String)